// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Secyud.Abp.Permissions;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Secyud.Abp.Permissions;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPermissionAppService), typeof(PermissionClientProxy))]
public partial class PermissionClientProxy : ClientProxyBase<IPermissionAppService>, IPermissionAppService
{
    public virtual async Task<List<PermissionGrantInfoDto>> GetListAsync(string groupName, string providerKey, string providerName)
    {
        return await RequestAsync<List<PermissionGrantInfoDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), groupName },
            { typeof(string), providerKey },
            { typeof(string), providerName }
        });
    }

    public virtual async Task<List<PermissionGroupInfoDto>> GetGroupsAsync()
    {
        return await RequestAsync<List<PermissionGroupInfoDto>>(nameof(GetGroupsAsync));
    }

    public virtual async Task UpdateAsync(string providerKey, string providerName, UpdatePermissionsDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), providerKey },
            { typeof(string), providerName },
            { typeof(UpdatePermissionsDto), input }
        });
    }
}
