namespace Secyud.Abp.Permissions.EntityFrameworkCore;

public class EfCorePermissionDefinitionRecordRepositoryTests : PermissionDefinitionRecordRepositoryTests<AbpPermissionsEntityFrameworkCoreTestModule>
{

}
